#Queries Educational Attainment Data from statistics.gov.scot
#with the helper package 'opendatascot'

library(devtools)
library(utils)
library(magrittr)
library(devtools)
library(renv)
library(opendatascot)

#install package which has been fixed to return appropriate refperiods
devtools::install_github("datasciencescotland/opendatascot", ref = "refPeriod-fix")

#query data at intermediate geography zone level
edu_data <- ods_dataset("educational-attainment-of-school-leavers", geography = "iz")

#store the SPARQL query generated by the opendatascot package
#this can be checked in the statistics.gov.scot SPARQL Query editor
edu_sparql_query <- ods_print_query("educational-attainment-of-school-leavers", geography = "iz")



